[workspace]
members = [
    "openssl",
    "openssl-errors",
    "openssl-macros",
    "openssl-sys"
]

[patch.crates-io]
bindgen = { git = "https://github.com/daviddrysdale/rust-bindgen", branch = "allowlist-file" }
