[workspace]
resolver = "2"
members = [
    "openssl",
    "openssl-errors",
    "openssl-macros",
    "openssl-sys",
    "systest",
]

[patch.crates-io]
openssl-src = { git = "https://github.com/alexcrichton/openssl-src-rs", branch = "no-module" }
