[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[features]
vendored = ["openssl-sys/vendored"]

# just to simplify CI
v101 = []
v102 = []
v110 = []

[dependencies]
libc = "0.2"
openssl-sys = { path = "../openssl-sys" }

[build-dependencies]
ctest = "0.1"
