//! ML-DSA bindings for BoringSSL
//!
//! This module re-exports ML-DSA types and functions from the bindgen-generated
//! BoringSSL bindings.

use super::*;

// Re-export ML-DSA types from bindgen
pub use super::{
    MLDSA44_private_key, MLDSA44_public_key, MLDSA65_private_key, MLDSA65_public_key,
    MLDSA87_private_key, MLDSA87_public_key,
};

// Re-export ML-DSA union types with user-friendly names
pub use super::MLDSA44_private_key__bindgen_ty_1 as MLDSA44_private_key_union;
pub use super::MLDSA44_public_key__bindgen_ty_1 as MLDSA44_public_key_union;
pub use super::MLDSA65_private_key__bindgen_ty_1 as MLDSA65_private_key_union;
pub use super::MLDSA65_public_key__bindgen_ty_1 as MLDSA65_public_key_union;
pub use super::MLDSA87_private_key__bindgen_ty_1 as MLDSA87_private_key_union;
pub use super::MLDSA87_public_key__bindgen_ty_1 as MLDSA87_public_key_union;

// Re-export ML-DSA functions from bindgen
pub use super::{
    MLDSA44_generate_key, MLDSA44_marshal_public_key, MLDSA44_parse_public_key,
    MLDSA44_private_key_from_seed, MLDSA44_public_from_private, MLDSA44_sign, MLDSA44_verify,
    MLDSA65_generate_key, MLDSA65_marshal_public_key, MLDSA65_parse_public_key,
    MLDSA65_private_key_from_seed, MLDSA65_public_from_private, MLDSA65_sign, MLDSA65_verify,
    MLDSA87_generate_key, MLDSA87_marshal_public_key, MLDSA87_parse_public_key,
    MLDSA87_private_key_from_seed, MLDSA87_public_from_private, MLDSA87_sign, MLDSA87_verify,
};

// Re-export CBB/CBS types and functions from bindgen
pub use super::cbb_st as CBB;
pub use super::CBS;
pub use super::{CBB_cleanup, CBB_data, CBB_init, CBB_len, CBB_zero};

// Constants (not generated by bindgen, must be defined manually)
pub const MLDSA_SEED_BYTES: usize = 32;
pub const MLDSA_MU_BYTES: usize = 64;

pub const MLDSA44_PUBLIC_KEY_BYTES: usize = 1312;
pub const MLDSA44_SIGNATURE_BYTES: usize = 2420;

pub const MLDSA65_PUBLIC_KEY_BYTES: usize = 1952;
pub const MLDSA65_SIGNATURE_BYTES: usize = 3309;

pub const MLDSA87_PUBLIC_KEY_BYTES: usize = 2592;
pub const MLDSA87_SIGNATURE_BYTES: usize = 4627;
